books/urls.py
from django.urls import path

from .views import BookDetailView, BooksListView, PublisherView

app_name = 'books'

urlpatterns = [
    path('', BooksListView.as_view(), name='books-list'),
    path('<int:pk>/', BookDetailView.as_view(), name='books-detail'),
    path('publisher/<int:pk>/', PublisherView.as_view(), name='publishers-detail'),
]

geeklib/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url=reverse_lazy('books:books-list'))),
    path('users/', include('users.urls', 'users')),
    path('admin/', admin.site.urls),
    path('books/', include('books.urls', 'books')),
    path('libraries/', include('libraries.urls', 'libraries')),
    path('__debug__/', include('debug_toolbar.urls')),
]

libraries/urls.py
from django.urls import path

from .views import BookRentDelete, LibraryBookDetail

app_name = 'libraries'

urlpatterns = [
    path('book/<int:pk>/', LibraryBookDetail.as_view(), name='books-detail'),
    path('book-rent/<int:pk>/return/', BookRentDelete.as_view(), name='book-return'),
]

users/urls.py
from django.contrib.auth.views import LoginView
from django.urls import include, path, reverse_lazy
from django.views.generic import CreateView

from .forms import SignupForm
from .views import ProfileView

app_name = 'users'

urlpatterns = [
    path('profile/', ProfileView.as_view(), name='profile'),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'register/',
        CreateView.as_view(
            template_name='users/signup.html',
            form_class=SignupForm,
            success_url=reverse_lazy('books:books-list')
        ),
        name='signup'
    ),
    path('', include('django.contrib.auth.urls')),
]

users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class SignupForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import ListView

User = get_user_model()


@method_decorator(login_required, 'dispatch')
class ProfileView(ListView):
    context_object_name = 'books'
    template_name = 'users/profile.html'
    paginate_by = 10

    def get_queryset(self, **kwargs):
        return self.request.user.rents.select_related()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['profile'] = self.request.user
        return context

users/templates/users/book_card.html
{% extends 'books/book_card.html' %}

{% block book_card_footer %}
  <div class="d-flex align-items-center justify-content-between">
    {{ rent.to_date }}
    <a class="btn btn-danger" href={% url 'libraries:book-return' rent.id %}>
      Return
    </a>
  </div>
{% endblock book_card_footer %}

users/templates/users/login.html
{% extends "base.html" %}
{% load user_filters %}
{% load static %}

{% block title %}
  Войти
{% endblock %}

{% block content %}
  <div class="row justify-content-center center-wrapper">
    <div class="col-md-5">
      <div class="card bg-dark">
        <div class="card-header">
          Login
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control bg-secondary text-light border-0' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-4 offset-md-4 d-flex flex-column">
            <button type="submit" class="btn btn-primary bg-custom-gradient">
              Login
            </button>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}

users/templates/users/profile.html
{% extends 'column_layout.html' %}

{% block aside_header %}
  {{ profile }}
{% endblock aside_header %}

{% block section_content %}
  {% for rent in books %}
    {% include 'users/book_card.html' with book=rent.book.book %}
  {% endfor %}
{% endblock section_content %}

users/templates/users/signup.html
{% extends 'base.html' %}
{% load user_filters %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-5 p-5">
      <div class="card bg-dark text-light">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}
              {% for field in form %} 
                <div class="form-group row my-3 mx-1">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {{ field|addclass:'form-control bg-secondary text-light border-0' }} 
                </div>
              {% endfor %}
              <div class="col-md-4 offset-md-4 d-flex flex-column">
                <button type="submit" class="btn btn-primary bg-custom-gradient">
                  Signup
                </button>
              </div>
              </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}