books/urls.py
from django.urls import path

from .views import BookDetailView, BooksListView, PublisherView

app_name = 'books'

urlpatterns = [
    path('', BooksListView.as_view(), name='books-list'),
    path('<int:pk>/', BookDetailView.as_view(), name='books-detail'),
    path('publisher/<int:pk>/', PublisherView.as_view(), name='publishers-detail'),
]

geeklib/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url=reverse_lazy('books:books-list'))),
    path('users/', include('users.urls', 'users')),
    path('admin/', admin.site.urls),
    path('books/', include('books.urls', 'books')),
    path('libraries/', include('libraries.urls', 'libraries')),
    path('__debug__/', include('debug_toolbar.urls')),
]

users/urls.py
from django.contrib.auth.views import LoginView
from django.urls import include, path, reverse_lazy
from django.views.generic import CreateView

from .forms import SignupForm
from .views import ProfileView

app_name = 'users'

urlpatterns = [
    path('profile/', ProfileView.as_view(), name='profile'),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'register/',
        CreateView.as_view(
            template_name='users/signup.html',
            form_class=SignupForm,
            success_url=reverse_lazy('books:books-list')
        ),
        name='signup'
    ),
    path('', include('django.contrib.auth.urls')),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/fontawesome.min.css" integrity="sha512-xX2rYBFJSj86W54Fyv1de80DWBq7zYLn2z0I9bIhQG+rxIF6XVJUpdGnsNHWRa6AvP89vtFupEPDP8eZAtu9qA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="{% static 'style.css' %}"/>
  {% block head %}{% endblock head %}
  <title>{% block title %}GeekLib{% endblock title %}</title>
</head>
<body class="text-light">
  {% include 'nav.html' %}
  <h1>{% block heading %}{% endblock heading %}</h1>
  <main>
    {% block content %}{% endblock content %}
  </main>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</body>
</html>

templates/column_layout.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-4">
      <div class="card bg-dark mt-3 p-2 px-3">
        {% block aside %}
        <div class="text-muted d-flex align-items-center justify-content-between">
          <h3 class="text-gradient mb-0">
            {% block aside_header %}{% endblock aside_header %}
          </h3>
          {% with books_count=paginator.count %}
          <span>
            {% if books_count == 0 %}
            No books
            {% elif books_count == 1 %}
            {{ books_count }} book
            {% elif books_count > 1 %}
            {{ books_count }} books
            {% endif %}
          </span>
          {% endwith %}
        </div>
          {% block aside_content %}{% endblock aside_content %}
        {% endblock aside %}
      </div>
    </div>
    <div class="col-md-6">
      {% block section_content %}
        {% for book in books %}
          {% include 'books/book_card.html' %}
        {% endfor %}
      {% endblock section_content %}
      <div class="d-flex justify-content-center">
        {% include 'paginator.html' %}
      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/default_form_fields.html
{% load user_filters %}

{% for field in form %}
  <div>
    <label>{{ field.label }}</label>
    {{ field|addclass:"form-control bg-dark text-light border-0" }}
  </div>
{% endfor %}

templates/inline_paginator.html
{% if is_paginated %}
<nav aria-label="" class="justify-content-center d-flex bg-dark">
  <ul class="pagination">
    {% for i in page_obj.paginator.page_range %}
      <li class="page-item {% if page_obj.number == i %}disabled{% else %} text-light{% endif %}">
        <a class="page-link bg-dark border-dark {% if page_obj.number == i %}disabled{% else %} text-light{% endif %}" href="?page={{ i }}">{{ i }}</a>
      </li>
    {% endfor %}
  </ul>
</nav>
{% endif %}

templates/nav.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand text-gradient" href={% url 'books:books-list' %}>GeekLib</a>
    <ul class="navbar-nav">
      {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href={% url 'users:profile' %}>{{ user.username }}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-danger" href={% url 'users:logout' %}>Logout</a>
        </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href={% url 'users:login' %}>Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href={% url 'users:signup' %}>Signup</a>
          </li>
      {% endif %}
    </ul>
  </div>
</nav>

templates/paginator.html
{% if is_paginated %}
  <nav class="paper" aria-label="product page navigation">
    <ul class="pagination pagination-md-sm m-0 p-2">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link bg-dark border-dark text-light" href="?page={{ page_obj.previous_page_number }}">
            &laquo;
            <span class="d-none d-md-inline"></span>
          </a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link bg-dark border-dark" href="#" tabindex="-1" aria-disabled="True">
            &laquo;
            <span class="d-none d-md-inline"></span>
          </a>
        </li>
      {% endif %}

      {% if page_obj.number|add:'-2' > 1 %}
        <li class="page-item">
          <a class="page-link d-none d-sm-block bg-dark border-dark" href="?page=1">1</a>
        </li>
        <li class="page-item">
          <a class="page-link d-none d-sm-block bg-dark border-dark" href="?page={{ page_obj.number|add:'-3' }}">&hellip;</a>
        </li>
      {% endif %}

      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active bg-dark border-dark" aria-current="page">
            <span class="page-link bg-secondary border-secondary text-dark">
              {{ i }}
            </span>
          </li>
        {% elif i > page_obj.number|add:'-3' and i < page_obj.number|add:'3' %}
          <li class="page-item">
            <a class="page-link bg-dark border-dark text-light" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}

      {% if page_obj.paginator.num_pages > page_obj.number|add:'2' %}
        <li class="page-item">
          <a class="page-link d-none d-sm-block bg-dark border-dark" href="?page={{ page_obj.number|add:'3' }}">&hellip;</a>
        </li>
        <li class="page-item">
          <a class="page-link d-none d-sm-block bg-dark border-dark" href="?page={{ page_obj.paginator.num_pages}}">{{ page_obj.paginator.num_pages }}</a>
        </li>
      {% endif %}



      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link bg-dark border-dark text-light" href="?page={{ page_obj.next_page_number }}">
            <span class="d-none d-md-inline"></span>
            &raquo;
          </a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link bg-dark border-dark" href="#" tabindex="-1" aria-disabled="True">
            <span class="d-none d-md-inline"></span>
            &raquo;
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

templates/plate_layout.html
{% extends 'base.html' %}

{% block content %}
<div class="center-wrapper container">
  {% block centralized_content %}
    <div class="card bg-dark col-7">
      {% block card_content %}
        {% block plate_header %}
          {% include 'books/book_card_header.html' %}
        {% endblock plate_header %}
        <div class="card-body row">
          {% block plate_content %}{% endblock plate_content %}
        </div>

        {% block plate_footer %}
          <div class="card-footer row align-items-center">
            <div class="col-6 align-self-start">
              <a href="javascript:history.back()" class="btn btn-secondary">
                Back
              </a>
            </div>
            <div class="col-6 d-flex justify-content-center">
              {% block footer_msg %}
                {% if not available_libraries %}
                <span class="text-warning">This book is unavalable for rent.</span>
                {% else %}
                <span class="text-muted">This book is available in {{ available_libraries.paginator.count }} libraries.</span>
                {% endif %}
              {% endblock footer_msg %}
            </div>
          </div>
        {% endblock plate_footer %}

      {% endblock card_content %}
    </div>
  {% endblock centralized_content %}
</div>
{% endblock content %}