books/urls.py
from django.urls import path

from .views import BookDetailView, BooksListView, PublisherView

app_name = 'books'

urlpatterns = [
    path('', BooksListView.as_view(), name='books-list'),
    path('<int:pk>/', BookDetailView.as_view(), name='books-detail'),
    path('publisher/<int:pk>/', PublisherView.as_view(), name='publishers-detail'),
]

geeklib/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url=reverse_lazy('books:books-list'))),
    path('users/', include('users.urls', 'users')),
    path('admin/', admin.site.urls),
    path('books/', include('books.urls', 'books')),
    path('libraries/', include('libraries.urls', 'libraries')),
    path('__debug__/', include('debug_toolbar.urls')),
]

libraries/urls.py
from django.urls import path

from .views import BookRentDelete, LibraryBookDetail

app_name = 'libraries'

urlpatterns = [
    path('book/<int:pk>/', LibraryBookDetail.as_view(), name='books-detail'),
    path('book-rent/<int:pk>/return/', BookRentDelete.as_view(), name='book-return'),
]

books/models.py
from django.db import models
from django.urls import reverse


class PublishsingHouse(models.Model):
    class Meta:
        verbose_name = 'Publishing House'
        verbose_name_plural = 'Publishing Houses'
        db_table = 'publishing_houses'

    name = models.CharField('publising house name', max_length=255)
    description = models.TextField(
        'publishing house description',
        max_length=200
    )

    def __str__(self) -> str:
        return self.name


class Book(models.Model):
    class Meta:
        verbose_name = 'Book'
        verbose_name_plural = 'Books'
        db_table = 'books'

    name = models.CharField('book name', max_length=255)
    short_description = models.TextField(
        'book short description', max_length=200,
    )
    description = models.TextField('book description')
    pub_date = models.DateField('Publishing Date')
    author = models.TextField('author`s name')
    publisher = models.ForeignKey(
        PublishsingHouse,
        on_delete=models.CASCADE,
        related_name='books',
        verbose_name='Publisher'
    )

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
        return reverse('books:books-detail', kwargs={'pk': self.pk})

books/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView, ListView

from geeklib.service.paginator import paginate_queryset

from .models import Book, PublishsingHouse


class BooksListView(ListView):
    queryset = Book.objects.select_related('publisher')
    context_object_name = 'books'
    template_name = 'books/index.html'
    paginate_by = 10


class BookDetailView(DetailView):
    queryset = Book.objects.select_related('publisher')
    context_object_name = 'book'
    template_name = 'books/book_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['available_libraries'] = paginate_queryset(
            self.request,
            self.object.available_libraries.select_related()
        )
        return context


class PublisherView(ListView):
    context_object_name = 'books'
    template_name = 'books/publisher.html'
    paginate_by = 10

    def get_queryset(self, **kwargs):
        self.publisher = get_object_or_404(
            PublishsingHouse, id=self.kwargs.get('pk')
        )
        return self.publisher.books.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['publishing_house'] = self.publisher
        return context

books/templates/books/book_card.html
<div class="card bg-dark mt-3">
  {% include 'books/book_card_header.html' %}
  <div class="card-body">
    {% if book.short_description %}
      <p class="card-text">{{ book.short_description }}</p>
    {% endif %}
    {% block book_card_footer %}
      <a href="{{ book.get_absolute_url }}" class="btn btn-primary bg-custom-gradient border-0">More</a>
    {% endblock book_card_footer %}
  </div>
</div>

books/templates/books/book_card_header.html
<div class="card-header d-flex align-items-center justify-content-between">
  <div class="d-flex align-items-center">
    <h3 class="card-title text-gradient">
      <a href={% url 'books:books-detail' book.id %}>
        {{ book }}
      </a>
    </h3>
    <span class="text-muted mx-2">by {{ book.author }}</span>
  </div>
  {% if not publishing_house %}
    <a href={% url 'books:publishers-detail' book.publisher.id %} class="text-muted">{{ book.publisher }}</a>
  {% endif%}
</div>

books/templates/books/book_detail.html
{% extends 'plate_layout.html' %}

{% block plate_content %}
  <div class="card-body row">
    <div class="col-6">
      {{ book.description }}
    </div>
    <div class="col-6 d-flex flex-column">
      {% if available_libraries %}
      <h4>
        Available in:
      </h4>
      <ul class="list-group list-group-flush">
        {% for lib_book in available_libraries %}
        <li class="list-group-item bg-dark text-light d-flex align-items-center justify-content-between">
          <span>{{ lib_book.library.name }}</span>
          <a href={% url 'libraries:books-detail' lib_book.id %} class="text-gradient">
            More
          </a>
        </li>
        {% endfor %}
      </ul>
      <div class="mt-auto">
        {% include 'inline_paginator.html' with is_paginated=True page_obj=available_libraries %}
      </div>
      {% endif %}
    </div>
  </div>
{% endblock plate_content %}

books/templates/books/index.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <div class="offset-3 col-md-6">
      {% for book in books %}
        {% include 'books/book_card.html' %}
      {% endfor %}
    </div>
  </div>
  <div class="d-flex justify-content-center">
    {% include 'paginator.html' %}
  </div>
{% endblock content %}

books/templates/books/publisher.html
{% extends 'column_layout.html' %}

{% block aside_header %}
  {{ publishing_house }}
{% endblock aside_header %}

{% block aside_content %}
  <div>
    {{ publishing_house.description }}
  </div>
{% endblock aside_content %}